### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by Canoncul** [ultraware/d-ORModel#1]
d-ORModel is good db library but i have a problem. when i close my application after database operations i see runtime error. how can i close my application without runtime error ?

**Comment by andremussche** [comment]
Can you make a simple demo application so I can reproduce it too?

E.g. can you try to create the error in the unit test project too?

2015-07-28 13:22 GMT+02:00 Canoncul notifications@github.com:

**Comment by andremussche** [comment]
I remember something similar due to finalisation order problems, can you
put some breakpoints in finalization sections or debug/step through it?
Op 28 jul. 2015 10:03 PM schreef "André Mussche" andre.mussche@gmail.com:

**Comment by Canoncul** [comment]
thank you for your help, i solve problem.i was create my object as object :=TXXXXCrud.create but your examples as object := XXXX;
i fix all code and working without errors now.
and thank you again, you did amazing job for all delphi community, i wish embarcadero will use your project in next delphi versions(my english is not very well, i am sorry)

Date: Tue, 28 Jul 2015 13:40:35 -0700

**Comment by andremussche** [comment]
Great to hear you have no errors using the singletons now! However it
should be possible to manually create and destroy multiple cruds, I will
take a look at this next week, after my holidays.

I hope i will have more time then too, for promoting this library. We use
it internally for all new projects, and we convert existing projects too.
Thank you for the positive comment!
Op 29 jul. 2015 11:07 AM schreef "Canoncul" notifications@github.com:

**Comment by Canoncul** [comment]
if you want i can create a blog for your project with turkish language for your promoting actions

Date: Wed, 29 Jul 2015 13:09:42 -0700

**Comment by andremussche** [comment]
A blog post will be very nice, but please let me fix the bug first next
week :-)
Op 30 jul. 2015 11:59 AM schreef "Canoncul" notifications@github.com:
